# Generated by Django 4.2.3 on 2023-07-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bereich', models.CharField(choices=[('K', 'Karosseriebau'), ('F', 'Fördertechnik'), ('M', 'Montage'), ('I', 'Inhouse Logistik'), ('P', 'Presswerk'), ('L', 'Lackiererei'), ('B', 'Batteriefertigung'), ('C', 'Komponente')], default=None, max_length=1)),
                ('segment', models.CharField(max_length=1)),
                ('anlage', models.CharField(max_length=4)),
                ('arg_sps', models.CharField(max_length=1)),
                ('pultbereich_sk', models.CharField(max_length=1)),
                ('station', models.CharField(max_length=4)),
                ('funktionseinheit', models.CharField(max_length=3)),
                ('profinet_name', models.CharField(default=None, editable=False, max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(choices=[('X1', 'X1'), ('X2', 'X2'), ('X3', 'X3'), ('X4', 'X4'), ('X5', 'X5'), ('X6', 'X6'), ('X7', 'X7'), ('X8', 'X8')], default=None, max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='max_musterman@volkswagen.de', max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('accessable_cabinets', models.CharField(max_length=500, null=True)),
                ('role', models.CharField(choices=[('TECHNICIAN', 'Technician'), ('PLANT_OPERATOR', 'Plant Operator'), ('IT_SHOPFLOOR', 'IT Shopfloor')], default=None, max_length=100)),
                ('bereich', models.CharField(choices=[('K', 'Karosseriebau'), ('F', 'Foerdertechnik'), ('M', 'Montage'), ('I', 'Inhouse Logistik'), ('P', 'Presswerk'), ('L', 'Lackiererei'), ('B', 'Batteriefertigung'), ('C', 'Komponente')], default=None, max_length=1)),
                ('telephone', models.CharField(max_length=15)),
                ('shift', models.CharField(choices=[('FRUEH', 'FRUEH'), ('SPAET', 'SPAET'), ('NACHT', 'NACHT')], default=None, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Io_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geraet', models.CharField(max_length=3)),
                ('module_type', models.CharField(choices=[('IO_LINK', 'IO_Link Master')], max_length=10)),
                ('profinet_address', models.GenericIPAddressField(default=None, unique=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('profinet_name', models.CharField(default=None, editable=False, max_length=18)),
                ('bereich', models.CharField(choices=[('K', 'Karosseriebau'), ('F', 'Fördertechnik'), ('M', 'Montage'), ('I', 'Inhouse Logistik'), ('P', 'Presswerk'), ('L', 'Lackiererei'), ('B', 'Batteriefertigung'), ('C', 'Komponente')], editable=False, max_length=1)),
                ('segment', models.CharField(editable=False, max_length=1)),
                ('anlage', models.CharField(editable=False, max_length=4)),
                ('arg_sps', models.CharField(editable=False, max_length=1)),
                ('pultbereich_sk', models.CharField(editable=False, max_length=1)),
                ('station', models.CharField(editable=False, max_length=4)),
                ('funktionseinheit', models.CharField(editable=False, max_length=3)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('profinet_name', models.CharField(default=None, editable=False, max_length=200)),
                ('direction', models.CharField(choices=[('FRONT', 'front'), ('BACK', 'back')], default=None, max_length=20)),
                ('section', models.CharField(choices=[('NETWORK', 'IT Network'), ('PS', 'Powe supply'), ('FE', 'Factory Edge Server')], default=None, max_length=20)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='Access_Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('accses_granted', models.BooleanField(default=False)),
                ('shift_time1_start', models.IntegerField(default=480)),
                ('shift_time1_end', models.IntegerField(default=870)),
                ('shift_time2_start', models.IntegerField(default=871)),
                ('shift_time2_end', models.IntegerField(default=1000)),
                ('shift_time3_start', models.IntegerField(default=1001)),
                ('shift_time3_end', models.IntegerField(default=1400)),
                ('cabinet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.cabinet')),
                ('door', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.door')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature_sensor',
            fields=[
                ('ports_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.ports')),
                ('module_type', models.CharField(choices=[('TEMP', 'Temperature sensor')], max_length=15)),
                ('measuring_env', models.CharField(choices=[('IN', 'inside'), ('OUT', 'outside')], default=None, max_length=7)),
                ('value_temperature', models.FloatField(default=0)),
                ('value_humidity', models.FloatField(default=0)),
                ('bmk', models.CharField(default=None, max_length=4)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('profinet_address', models.GenericIPAddressField(default=None, editable=False)),
                ('profinet_name', models.CharField(default=None, editable=False, max_length=22)),
                ('bereich', models.CharField(choices=[('K', 'Karosseriebau'), ('F', 'Fördertechnik'), ('M', 'Montage'), ('I', 'Inhouse Logistik'), ('P', 'Presswerk'), ('L', 'Lackiererei'), ('B', 'Batteriefertigung'), ('C', 'Komponente')], editable=False, max_length=1)),
                ('segment', models.CharField(editable=False, max_length=1)),
                ('anlage', models.CharField(editable=False, max_length=4)),
                ('arg_sps', models.CharField(editable=False, max_length=1)),
                ('pultbereich_sk', models.CharField(editable=False, max_length=1)),
                ('station', models.CharField(editable=False, max_length=4)),
                ('funktionseinheit', models.CharField(editable=False, max_length=3)),
                ('geraet', models.CharField(editable=False, max_length=3)),
                ('iolink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.io_link')),
            ],
            bases=('web.ports',),
        ),
        migrations.CreateModel(
            name='Lock_actuator',
            fields=[
                ('ports_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.ports')),
                ('module_type', models.CharField(choices=[('LOCK', 'Lock actuator')], max_length=20)),
                ('bmk', models.CharField(default=None, max_length=4)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('profinet_address', models.GenericIPAddressField(default=None, editable=False)),
                ('profinet_name', models.CharField(default=None, editable=False, max_length=22)),
                ('bereich', models.CharField(choices=[('K', 'Karosseriebau'), ('F', 'Fördertechnik'), ('M', 'Montage'), ('I', 'Inhouse Logistik'), ('P', 'Presswerk'), ('L', 'Lackiererei'), ('B', 'Batteriefertigung'), ('C', 'Komponente')], editable=False, max_length=1)),
                ('segment', models.CharField(editable=False, max_length=1)),
                ('anlage', models.CharField(editable=False, max_length=4)),
                ('arg_sps', models.CharField(editable=False, max_length=1)),
                ('pultbereich_sk', models.CharField(editable=False, max_length=1)),
                ('station', models.CharField(editable=False, max_length=4)),
                ('funktionseinheit', models.CharField(editable=False, max_length=3)),
                ('geraet', models.CharField(editable=False, max_length=3)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.door')),
                ('iolink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.io_link')),
            ],
            bases=('web.ports',),
        ),
        migrations.CreateModel(
            name='Led',
            fields=[
                ('ports_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.ports')),
                ('module_type', models.CharField(choices=[('LED', 'Signal LED')], max_length=20)),
                ('bmk', models.CharField(default=None, max_length=3)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('profinet_address', models.GenericIPAddressField(default=None, editable=False)),
                ('profinet_name', models.CharField(default=None, editable=False, max_length=22)),
                ('bereich', models.CharField(choices=[('K', 'Karosseriebau'), ('F', 'Fördertechnik'), ('M', 'Montage'), ('I', 'Inhouse Logistik'), ('P', 'Presswerk'), ('L', 'Lackiererei'), ('B', 'Batteriefertigung'), ('C', 'Komponente')], editable=False, max_length=1)),
                ('segment', models.CharField(editable=False, max_length=1)),
                ('anlage', models.CharField(editable=False, max_length=4)),
                ('arg_sps', models.CharField(editable=False, max_length=1)),
                ('pultbereich_sk', models.CharField(editable=False, max_length=1)),
                ('station', models.CharField(editable=False, max_length=4)),
                ('funktionseinheit', models.CharField(editable=False, max_length=3)),
                ('geraet', models.CharField(editable=False, max_length=3)),
                ('iolink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.io_link')),
            ],
            bases=('web.ports',),
        ),
    ]
