# Generated by Django 4.2.3 on 2023-11-05 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='direction',
            field=models.CharField(choices=[('Front', 'Front'), ('Rear', 'Rear')], max_length=16),
        ),
        migrations.AlterField(
            model_name='door',
            name='qr',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Edge_A', 'Edge_A'), ('Edge_B', 'Edge_B'), ('Network', 'Network'), ('Energy', 'Energy'), ('Cooling', 'Cooling')], default=None, max_length=16)),
                ('qr', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cabinet')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='door',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='door',
            name='rack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rack', to='web.rack'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='door',
            unique_together={('direction', 'rack')},
        ),
        migrations.RemoveField(
            model_name='door',
            name='name',
        ),
        migrations.RemoveField(
            model_name='door',
            name='profinet_name',
        ),
        migrations.RemoveField(
            model_name='door',
            name='section',
        ),
    ]
