# Generated by Django 4.2.3 on 2023-07-26 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='qr',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='anlage',
            field=models.CharField(help_text='it must have at least four character', max_length=4),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='segment',
            field=models.CharField(help_text='it must have at least one character', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='max_musterman@volkswagen.de', max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='door',
            unique_together={('name', 'cabinet')},
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
        ),
        migrations.CreateModel(
            name='Door_sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('Door_Sensor', 'Door Sensor')], max_length=20)),
                ('bmk', models.CharField(default=None, max_length=4)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('profinet_address', models.GenericIPAddressField(default=None, editable=False)),
                ('profinet_name', models.CharField(default=None, editable=False, max_length=22)),
                ('value', models.BooleanField(default=False)),
                ('bereich', models.CharField(choices=[('K', 'Karosseriebau'), ('F', 'Fördertechnik'), ('M', 'Montage'), ('I', 'Inhouse Logistik'), ('P', 'Presswerk'), ('L', 'Lackiererei'), ('B', 'Batteriefertigung'), ('C', 'Komponente')], editable=False, max_length=1)),
                ('segment', models.CharField(editable=False, max_length=1)),
                ('anlage', models.CharField(editable=False, max_length=4)),
                ('arg_sps', models.CharField(editable=False, max_length=1)),
                ('pultbereich_sk', models.CharField(editable=False, max_length=1)),
                ('station', models.CharField(editable=False, max_length=4)),
                ('funktionseinheit', models.CharField(editable=False, max_length=3)),
                ('geraet', models.CharField(editable=False, max_length=3)),
                ('iolink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.io_link')),
            ],
        ),
        migrations.RemoveField(
            model_name='door',
            name='profinet_name',
        ),
        migrations.RemoveField(
            model_name='door',
            name='qr_code',
        ),
    ]
