# Generated by Django 4.2.3 on 2023-11-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plc',
            name='profinet_name',
            field=models.CharField(default=None, editable=False, max_length=32, unique=True),
        ),
    ]
