# Generated by Django 4.2.3 on 2023-07-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_door_qr_code_door_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='max_musterman@volkswagen.de', max_length=254, unique=True),
        ),
    ]
