# Generated by Django 4.2.4 on 2023-08-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_delete_json_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Json_draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(default='request', max_length=64)),
                ('cid', models.IntegerField(default=4711)),
                ('adr', models.CharField(default='/iolinkmaster/port[2]/iolinkdevice/pdin/getdata', max_length=128)),
                ('url', models.URLField(default='http://192.168.0.4', max_length=32)),
                ('data', models.TextField(blank=True, max_length=256)),
                ('payload', models.TextField(editable=False, max_length=512)),
                ('moethod', models.CharField(default='POST', max_length=16)),
            ],
        ),
    ]
