# Generated by Django 4.2.3 on 2023-07-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='door',
            unique_together={('name', 'cabinet')},
        ),
        migrations.RemoveField(
            model_name='door',
            name='profinet_name',
        ),
    ]
