# Generated by Django 4.2.3 on 2023-11-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_buttonvalue_time_alter_doorsensorvalue_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturesensorvalue',
            name='valid',
            field=models.BooleanField(null=True),
        ),
    ]
