# Generated by Django 4.2.3 on 2023-07-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
