# Generated by Django 4.2.3 on 2023-11-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_temperaturesensorvalue_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorsensorvalue',
            name='valid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='energysensorvalue',
            name='valid',
            field=models.BooleanField(null=True),
        ),
    ]
