# Generated by Django 4.2.3 on 2023-11-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_latchsensorvalue_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorsensorvalue',
            name='valid',
            field=models.BooleanField(null=True),
        ),
    ]
