# Generated by Django 4.2.3 on 2023-12-02 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_doorsensorvalue_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='plc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='web.plc'),
        ),
        migrations.AlterField(
            model_name='device',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='web.rack'),
        ),
    ]
